name: "Minecraft Server"
version: "2023.1.0"
slug: minecraft-server
description: "Minecraft server with dynamic version, server types, and modpack support "
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/itzg/docker-minecraft-server"
ports:
  25565/tcp: 25565
ports_description:
  25565/tcp: Standard Minecraft (Dedicated) Server
environment:
  EULA: true
image: itzg/minecraft-server
